version: "3"

services:
  noticeboard:
    build: .
    expose:
      - "3001"
    ports:
      - "4000:3001"
    depends_on:
      - noticeboarddb
    environment:
      PGHOST: noticeboarddb
      PGDATABASE: notices
      PGUSER: notices_robot
      PGPASSWORD: "n0t!c3s"

  noticeboarddb:
    build:
      context: .
      dockerfile: ./devdatabase/Dockerfile

    volumes:
      - ./devdatabase/volume:/var/lib/postgresql/data
    expose:
      - "5432"

    environment:
      POSTGRES_PASSWORD: pgsqlDev01
