version: "3"

services:
  noticeboard:
    build: .
    expose:
      - "3001"
    ports:
      - "4000:3001"
    depends_on:
      - noticeboarddb
    environment:
      DATABASE_HOST: noticeboarddb
      DATABASE_NAME: notices
      DATABASE_USER: notices_robot
      DATABASE_PASSWORD: "n0t!c3s"
      REDISHOST: noticeboardredis

  noticeboarddb:
    build:
      context: .
      dockerfile: ./devdatabase/Dockerfile

    volumes:
      - ./devdatabase/volume:/var/lib/postgresql/data
    expose:
      - "5432"

    environment:
      POSTGRES_PASSWORD: pgsqlDev01

  noticeboardredis:
    image: redis
    expose:
      - 6379
